#!/bin/zsh

arg1=${1}
arg2=${2}

#step-1
echo "\\\begin{center}" > temp.tex
echo "\\\begin{tikzpicture}" >> temp.tex


#step-2
($arg1 | awk $arg2 )| awk '{}END{print "\\draw[rounded corners] (0, 0) rectangle (10, " NR/2 + 1 ");\n\\draw[-Stealth, ultra thick] (0.5, " NR/2 + 0.5 ") -- (0.6, " NR/2 + 0.5 ");"}' >> temp.tex

#step-3
arg=$(echo $arg2 | awk '{gsub(/\{/, "\\\\{"); gsub(/\}/, "\\\\}"); gsub(/\$/, "\\\\$"); gsub(/\^/, "\\\\string\^"); print }')
($arg1 | awk $arg2) | awk -v t="$arg1" -v tt="$arg"  '{}END{print "\\node at (0.6, " NR/2 + 0.5 ")[right, text width=9cm] \{\\texttt\{" t " \| awk \$\47\$" tt "\$\47\$ \}\};"}' >> temp.tex


#step-4
n=$(($arg1 | awk $arg2)| awk '{}END{print NR}')
($arg1 | awk $arg2) | awk -v y="$n" '{gsub(/_/, "\\_"); print "\\node at (0.6, " y/2 + x")[right, text width=9cm] \{\\texttt\{" $0 "\}\};"; x-=0.5 }' >> temp.tex

#step-5
echo "\\\end{tikzpicture}" >> temp.tex
echo "\\\end{center}" >> temp.tex


