#!/bin/zsh

n=${1:-3}
output=${2:-box}

echo "Loading the SQLite database..."
sleep 0.75
echo " "


python3.9 /Users/vaibhavblayer/sqlite-projects/ciphered/deciphered.py $n
awk -v var="$output" 'NR == 1 {print ".mode "var}' /Users/vaibhavblayer/scripts/ciphered > sq
awk -v var="$n" 'NR == 2 {print "select rowid,  * from deciphered order by rowid desc limit "var ";"}' /Users/vaibhavblayer/scripts/ciphered >> sq


/usr/local/Cellar/sqlite/3.38.2/bin/sqlite3  /Users/vaibhavblayer/sqlite-projects/ciphered/ciphered.db ".read sq" 


rm sq




