#!/bin/zsh

day=$(date +%d%m%y)
time=$(date +%H%M)
part="M"
title="entropy"
level="3"
width="4.5"
bg="white!85!orange"
fg="white!10!purple"
partcolor="white!20!purple"
levelcolor="white!20!purple"
. /Users/vaibhavblayer/scripts/functions-for-gen-phys-eqn

while getopts :hp:P:t:l:L:w:b:f:: opt
do
	case "$opt" in
	h) help
	   exit ;;
	p) part=$OPTARG ;;
	P) partcolor=$OPTARG ;;
	t) title=$OPTARG ;;
	l) level=$OPTARG ;;
	L) levelcolor=$OPTARG ;;
	w) width=$OPTARG ;;
	b) bg=$OPTARG ;;
	f) fg=$OPTARG ;;
	*) echo "$opt" ;;
	esac
done


createSkeleton $day $part $time
insertDimension $width
insertTopic $day $part $time $partcolor
insertBackgroundColor $bg
insertForegroundColor $fg
insertLevel $level $levelcolor
insertTitle $title
insertTikzEnv
insertEquation

printf "\\\vspace*{\\\fill}\n\\\end{document}" >> main.tex

open -a texmaker preamble.sty main.tex

